### PR TITLE
Include virtualchannel test

### LINKED ISSUE #20: Add missing client tests
### Location
package `client`

### Problem
We have generic tests for all the client functionality in go-perun core, but not all are used here in the Perun Ethereum Backend. In particular, the following would be important to integrate here:

- [ ] Virtual channel happy and dispute test.
- [x] Subchannel happy and dispute test.
- [x] Failed funding test.

### Proposal
Have a look at the generic client tests in go-perun and integrate them here.

### PR DESCRIPTION
**Pull request by matthiasgeihs**
This adds the virtual channel test.

Closes #20.

Depends on https://github.com/hyperledger-labs/go-perun/pull/375.

### CODE REVIEW

File: client/virtualchannel_test.go [hunk 1]
```diff
@@ -0,0 +1,86 @@
...
+	ctest.TestVirtualChannelDispute(
+		ctx,
+		t,
+		createVirtualChannelSetup(t, rng),
+	)
+}
+
+func createVirtualChannelSetup(t *testing.T, rng *rand.Rand) ctest.VirtualChannelSetup {
+	t.Helper()
+	clients, asset := setupVirtualChannelClients(t, rng)
```
Comment (cryptphil) [inline client/virtualchannel_test.go:57]: Couldn't you include the `setupVirtualChannelClients` code just inside this one or is it used somewhere else?

**Review by cryptphil — CHANGES_REQUESTED** [review]

File: client/virtualchannel_test.go (hunk 1 above)
Comment (matthiasgeihs) [reply client/virtualchannel_test.go:57]: I could, but what would be the benefit? Like this I think it is more readable.

**Review by cryptphil — APPROVED** [review]
